<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\LatestVehicle;
use Carbon\Carbon;

class LatestVehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing vehicles
        LatestVehicle::truncate();

        $vehicles = [
            [
                'manufacturer' => 'Lamborghini',
                'model' => 'Revuelto',
                'year' => 2024,
                'name' => 'Lamborghini Revuelto',
                'description' => 'The first V12 hybrid supercar from Lamborghini, combining a 6.5L V12 engine with three electric motors for unprecedented performance.',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                ],
                'price' => 608358.00,
                'currency' => 'EUR',
                'engine_type' => 'Hybrid',
                'engine_size' => '6.5L',
                'horsepower' => 1015,
                'torque' => 725,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 12.5,
                'co2_emissions' => 285,
                'body_type' => 'Supercar',
                'features' => [
                    'V12 Hybrid Powertrain',
                    'Aerodynamic Design',
                    'Active Aerodynamics',
                    'Lamborghini Infotainment System',
                    'Carbon Fiber Monocoque',
                    'Launch Control',
                ],
                'specifications' => [
                    'top_speed' => '350 km/h',
                    'acceleration' => '2.5s (0-100 km/h)',
                    'electric_range' => '10 km',
                    'total_power' => '1015 HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 1,
                'released_at' => Carbon::now()->subMonths(1),
            ],
            [
                'manufacturer' => 'Ferrari',
                'model' => 'SF90 Stradale',
                'year' => 2024,
                'name' => 'Ferrari SF90 Stradale',
                'description' => 'Ferrari\'s most powerful production car ever, featuring a twin-turbo V8 hybrid powertrain delivering Formula 1 technology for the road.',
                'image_url' => 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',
                ],
                'price' => 625000.00,
                'currency' => 'EUR',
                'engine_type' => 'Hybrid',
                'engine_size' => '4.0L',
                'horsepower' => 1000,
                'torque' => 800,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 11.5,
                'co2_emissions' => 260,
                'body_type' => 'Supercar',
                'features' => [
                    'Twin-Turbo V8 Hybrid',
                    'F1-Derived Technology',
                    'E-Diff Electronic Differential',
                    'Ferrari Dynamic Enhancer',
                    'Carbon Fiber Body',
                    'Active Aerodynamics',
                ],
                'specifications' => [
                    'top_speed' => '340 km/h',
                    'acceleration' => '2.5s (0-100 km/h)',
                    'electric_range' => '25 km',
                    'total_power' => '1000 HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 2,
                'released_at' => Carbon::now()->subMonths(2),
            ],
            [
                'manufacturer' => 'Porsche',
                'model' => '911 Turbo S',
                'year' => 2024,
                'name' => 'Porsche 911 Turbo S',
                'description' => 'The ultimate expression of the 911, combining legendary performance with everyday usability and cutting-edge technology.',
                'image_url' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
                ],
                'price' => 230000.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '3.8L',
                'horsepower' => 650,
                'torque' => 800,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 4,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 11.1,
                'co2_emissions' => 253,
                'body_type' => 'Sports Car',
                'features' => [
                    'Twin-Turbo Flat-6 Engine',
                    'Porsche Traction Management',
                    'PASM Adaptive Suspension',
                    'Sport Chrono Package',
                    'Carbon Ceramic Brakes',
                    'Active Aerodynamics',
                ],
                'specifications' => [
                    'top_speed' => '330 km/h',
                    'acceleration' => '2.7s (0-100 km/h)',
                    'nurburgring_time' => '7:17',
                    'power_to_weight' => '3.1 kg/HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 3,
                'released_at' => Carbon::now()->subMonths(1),
            ],
            [
                'manufacturer' => 'Aston Martin',
                'model' => 'DB12',
                'year' => 2024,
                'name' => 'Aston Martin DB12',
                'description' => 'The world\'s first "Super Tourer" - a new generation of Aston Martin that combines GT luxury with supercar performance.',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                ],
                'price' => 245000.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '4.0L',
                'horsepower' => 680,
                'torque' => 800,
                'transmission' => 'Automatic',
                'drivetrain' => 'RWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 12.0,
                'co2_emissions' => 272,
                'body_type' => 'Grand Tourer',
                'features' => [
                    'Twin-Turbo V8 Engine',
                    'Aston Martin Infotainment System',
                    'Adaptive Damping',
                    'Carbon Ceramic Brakes',
                    'Handcrafted Interior',
                    'Bowers & Wilkins Sound',
                ],
                'specifications' => [
                    'top_speed' => '325 km/h',
                    'acceleration' => '3.6s (0-100 km/h)',
                    'torque' => '800 Nm',
                    'weight' => '1685 kg',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 4,
                'released_at' => Carbon::now()->subMonths(3),
            ],
            [
                'manufacturer' => 'BMW',
                'model' => 'M8 Competition',
                'year' => 2024,
                'name' => 'BMW M8 Competition Coupe',
                'description' => 'The pinnacle of BMW M performance, combining luxury, technology, and track-ready performance in one stunning package.',
                'image_url' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
                ],
                'price' => 165000.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '4.4L',
                'horsepower' => 625,
                'torque' => 750,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 4,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 10.8,
                'co2_emissions' => 246,
                'body_type' => 'Coupe',
                'features' => [
                    'Twin-Turbo V8 Engine',
                    'M xDrive All-Wheel Drive',
                    'Active M Differential',
                    'M Sport Exhaust',
                    'Carbon Fiber Roof',
                    'M Carbon Ceramic Brakes',
                ],
                'specifications' => [
                    'top_speed' => '305 km/h',
                    'acceleration' => '3.2s (0-100 km/h)',
                    'nurburgring_time' => '7:32',
                    'power_to_weight' => '2.6 kg/HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 5,
                'released_at' => Carbon::now()->subMonths(2),
            ],
            [
                'manufacturer' => 'McLaren',
                'model' => 'Artura',
                'year' => 2024,
                'name' => 'McLaren Artura',
                'description' => 'McLaren\'s next-generation supercar, featuring a new V6 hybrid powertrain and cutting-edge lightweight architecture.',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                ],
                'price' => 225000.00,
                'currency' => 'EUR',
                'engine_type' => 'Hybrid',
                'engine_size' => '3.0L',
                'horsepower' => 680,
                'torque' => 720,
                'transmission' => 'Automatic',
                'drivetrain' => 'RWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 5.9,
                'co2_emissions' => 134,
                'body_type' => 'Supercar',
                'features' => [
                    'V6 Hybrid Powertrain',
                    'Carbon Fiber Monocoque',
                    'Active Dynamics System',
                    'McLaren Infotainment System',
                    'Lightweight Architecture',
                    'Electric-Only Mode',
                ],
                'specifications' => [
                    'top_speed' => '330 km/h',
                    'acceleration' => '3.0s (0-100 km/h)',
                    'electric_range' => '31 km',
                    'total_power' => '680 HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 6,
                'released_at' => Carbon::now()->subMonths(4),
            ],
            [
                'manufacturer' => 'Mercedes-AMG',
                'model' => 'GT 63 S E Performance',
                'year' => 2024,
                'name' => 'Mercedes-AMG GT 63 S E Performance',
                'description' => 'The most powerful AMG production car ever built, combining a V8 biturbo engine with hybrid technology for 843 HP.',
                'image_url' => 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
                ],
                'price' => 220000.00,
                'currency' => 'EUR',
                'engine_type' => 'Hybrid',
                'engine_size' => '4.0L',
                'horsepower' => 843,
                'torque' => 1470,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 4,
                'doors' => 4,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 8.6,
                'co2_emissions' => '196',
                'body_type' => 'Sedan',
                'features' => [
                    'V8 Biturbo Hybrid',
                    'AMG Performance 4MATIC+',
                    'AMG Ride Control+',
                    'AMG Track Package',
                    'Carbon Fiber Elements',
                    'AMG Sound Experience',
                ],
                'specifications' => [
                    'top_speed' => '316 km/h',
                    'acceleration' => '2.9s (0-100 km/h)',
                    'electric_power' => '204 HP',
                    'total_torque' => '1470 Nm',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 7,
                'released_at' => Carbon::now()->subMonths(1),
            ],
            [
                'manufacturer' => 'Audi',
                'model' => 'RS6 Avant',
                'year' => 2024,
                'name' => 'Audi RS6 Avant Performance',
                'description' => 'The ultimate high-performance estate car, combining supercar performance with practical everyday usability.',
                'image_url' => 'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1606664515524-ed2f786a0ad6?w=800',
                ],
                'price' => 135000.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '4.0L',
                'horsepower' => 630,
                'torque' => 850,
                'transmission' => 'Automatic',
                'drivetrain' => 'AWD',
                'seats' => 5,
                'doors' => 5,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => '11.7',
                'co2_emissions' => 266,
                'body_type' => 'Estate',
                'features' => [
                    'Twin-Turbo V8 Engine',
                    'quattro All-Wheel Drive',
                    'RS Adaptive Air Suspension',
                    'RS Sport Exhaust',
                    'Carbon Fiber Package',
                    'Matrix LED Headlights',
                ],
                'specifications' => [
                    'top_speed' => '305 km/h',
                    'acceleration' => '3.4s (0-100 km/h)',
                    'cargo_volume' => '565 liters',
                    'towing_capacity' => '2100 kg',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 8,
                'released_at' => Carbon::now()->subMonths(2),
            ],
            [
                'manufacturer' => 'Lamborghini',
                'model' => 'Huracán STO',
                'year' => 2024,
                'name' => 'Lamborghini Huracán STO',
                'description' => 'A road-legal race car inspired by the Huracán Super Trofeo EVO, delivering track-focused performance with street legality.',
                'image_url' => 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
                ],
                'price' => 327838.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '5.2L',
                'horsepower' => 640,
                'torque' => 565,
                'transmission' => 'Automatic',
                'drivetrain' => 'RWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => 13.5,
                'co2_emissions' => 308,
                'body_type' => 'Supercar',
                'features' => [
                    'Naturally Aspirated V10',
                    'Aerodynamic Body Kit',
                    'Carbon Fiber Monocoque',
                    'Race Mode Suspension',
                    'Brembo Carbon Ceramic Brakes',
                    'Trofeo Mode',
                ],
                'specifications' => [
                    'top_speed' => '310 km/h',
                    'acceleration' => '3.0s (0-100 km/h)',
                    'weight' => '1339 kg',
                    'power_to_weight' => '2.1 kg/HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 9,
                'released_at' => Carbon::now()->subMonths(3),
            ],
            [
                'manufacturer' => 'Ferrari',
                'model' => 'Roma',
                'year' => 2024,
                'name' => 'Ferrari Roma',
                'description' => 'A contemporary 2+ coupe that represents the pinnacle of performance in this category, combining refined elegance with sporty personality.',
                'image_url' => 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',
                ],
                'price' => 200000.00,
                'currency' => 'EUR',
                'engine_type' => 'Petrol',
                'engine_size' => '3.9L',
                'horsepower' => 620,
                'torque' => 760,
                'transmission' => 'Automatic',
                'drivetrain' => 'RWD',
                'seats' => 2,
                'doors' => 2,
                'fuel_type' => 'Petrol',
                'fuel_consumption' => '10.2',
                'co2_emissions' => 232,
                'body_type' => 'Coupe',
                'features' => [
                    'Twin-Turbo V8 Engine',
                    'Ferrari Dynamic Enhancer',
                    'Side Slip Control',
                    'Ferrari Infotainment System',
                    'Carbon Fiber Interior',
                    'Active Aerodynamics',
                ],
                'specifications' => [
                    'top_speed' => '320 km/h',
                    'acceleration' => '3.4s (0-100 km/h)',
                    'weight' => '1472 kg',
                    'power_to_weight' => '2.4 kg/HP',
                ],
                'status' => 'available',
                'is_featured' => true,
                'order' => 10,
                'released_at' => Carbon::now()->subMonths(4),
            ],
        ];

        foreach ($vehicles as $vehicle) {
            LatestVehicle::create($vehicle);
        }
    }
}
